os:
  - osx
language: cpp
compiler:
  - gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libboost-all-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install maven; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install cpp-coveralls wheel; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost-python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
script:
  - make
  - make python
  - cd java; mvn test; cd ..
  - make test
  - make test_gcov --always-make
  - python setup.py sdist
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py bdist_wheel; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py bdist_mpkg; fi
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
