os: 
  - osx
language: cpp
compiler:
  - gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libboost-all-dev
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install maven
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install cpp-coveralls wheel
script:
  - make
  - make python
  - cd java && mvn test && cd ..
  - make test
  - make test_gcov --always-make
  - python setup.py sdist
  - python setup.py bdist_wheel
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
