version: 1.0.{build}
os: Windows Server 2012 R2
configuration:
- Release
platform: x64
shallow_clone: true
clone_folder: C:\vowpal_wabbit
build:
  project: C:\vowpal_wabbit\vowpalwabbit\vw.sln
  parallel: true
  verbosity: detailed
after_build:
- cd cs
- ..\vowpalwabbit\.nuget\nuget pack cs.csproj -Prop "Configuration=Release;Platform=x64" -Prop SolutionDir=..\vowpalwabbit\ -OutputDirectory bin\x64\Release
test_script:
- ps: >-
    if($env:PLATFORM -eq "x64")

    {
       vstest.console /logger:Appveyor /Platform:x64 $env:APPVEYOR_BUILD_FOLDER\cs_unittest\bin\x64\$env:configuration\cs_unittest.dll
    }
